# Generated by Django 4.1.3 on 2022-12-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Embalaje',
            fields=[
                ('idEmbalaje', models.AutoField(primary_key=True, serialize=False)),
                ('embalaje', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('marca_marcaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('codigoMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateField()),
                ('fechaIngreso', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('idTipoMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('tipoProducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('idUnidadMedida', models.AutoField(primary_key=True, serialize=False)),
                ('unidadMedida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
                ('region_regionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.region')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('comuna_comunaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaVencimiento', models.DateField(null=True)),
                ('categoria_categoriaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.categoria')),
                ('embalaje_embalajeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.embalaje')),
                ('modelo_modeloId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.modelo')),
                ('movimiento_codigoMovimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.movimiento')),
                ('proveedor_rutProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.proveedor')),
                ('tipoProducto_tipoProductoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.tipoproducto')),
                ('unidadMedida_unidadMedidaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.unidadmedida')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipoMovimiento_tipoMovimientoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.tipomovimiento'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia_provinciaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioAPP.provincia'),
        ),
    ]
