# Generated by Django 4.1.3 on 2022-12-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioAPP', '0002_rol_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
