# Generated by Django 4.1.3 on 2022-12-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioAPP', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
