# Generated by Django 4.1.3 on 2022-12-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioAPP', '0006_alter_producto_fechavencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fechaVencimiento',
        ),
    ]
