# Generated by Django 4.1.3 on 2022-12-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioAPP', '0007_remove_producto_fechavencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
